apiVersion: v1
kind: Secret
metadata:
  name: frontend-postgresql
  namespace: default
  labels:
    app: frontend-postgresql
type: Opaque
data:
  postgresql-password: MjkzZjJjY2E0ZmIzZDEyZGU5NzFhYmIwNzhhNjA2MWYzOTdjNzg5NDQ3MjMzZjFmMGEwYzkxZjc0NTVh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-postgresql
  template:
    metadata:
      labels:
        app: frontend-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.3
          env:
            - name: POSTGRES_USER
              value: frontend
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frontend-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-postgresql
  namespace: default
spec:
  selector:
    app: frontend-postgresql
  ports:
    - port: 5432
